# Default values for log-collector.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  pullPolicy: IfNotPresent
  elasticsearch: 
    repository: docker.elastic.co/elasticsearch/elasticsearch
    tag: 7.3.2
  kibana:
    repository: docker.elastic.co/kibana/kibana
    tag: 7.3.2
    